package logic;

public enum CommandName {
    LOGIN,
    REGISTER,
    LOGOUT,
    GET_QUESTIONS,
    GET_QUESTION,
    ADD_QUESTION,
    EDIT_QUESTION,
    DELETE_QUESTION,
    GET_MESSAGES,
    RATE_MESSAGE,
    ADD_MESSAGE,
    EDIT_MESSAGE,
    DELETE_MESSAGE,
    GET_USERS,
    EDIT_USER,
    DELETE_USER,
    CHANGE_LANGUAGE,
    NO_SUCH_COMMAND,
}
